### ISSUE TITLE
alsa-lib-1.2.7.2/src/pcm/pcm.c:3238 triggers SIGSEGV

### ISSUE THREAD

**Issue by mmokrejs** [alsa-project/alsa-lib#274]
Hi,
  I tried an example command `espeak-ng "This is a test"` command but it crahes inside `libasound2`.

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `espeak-ng This is a test'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f672678ea6b in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f6725d4d640 (LWP 9533))]
(gdb) where
#0  0x00007f672678ea6b in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#1  0x00007f6726492ffd in snd_pcm_area_copy (dst_area=0x7f672001fc90, dst_offset=18, src_area=0x7f672002a4c0, src_offset=0, samples=4026531840, format=SND_PCM_FORMAT_S16_LE) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm.c:3238
#2  0x00007f67264934af in snd_pcm_areas_copy (dst_areas=0x7f672001fca0, dst_offset=18, src_areas=0x7f672002a4d0, src_offset=0, channels=1, frames=18446744073709551608, format=SND_PCM_FORMAT_S16_LE) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm.c:3389
#3  0x00007f67264ba368 in snd_pcm_rate_commit_area (pcm=0x7f6720061cf0, rate=0x7f6720061b00, appl_offset=7508, size=10, slave_size=22) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm_rate.c:817
#4  0x00007f67264bb217 in snd_pcm_rate_drain (pcm=0x7f6720061cf0) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm_rate.c:1161
#5  0x00007f6726490548 in snd_pcm_drain (pcm=0x7f6720061700) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm.c:1359
#6  0x00007f67266347e2 in alsa_object_drain () from /usr/lib64/libpcaudio.so.0
#7  0x00007f6726873c4e in sync_espeak_Synth () from /usr/lib64/libespeak-ng.so.1
#8  0x00007f672688e813 in process_espeak_command () from /usr/lib64/libespeak-ng.so.1
#9  0x00007f672688f708 in say_thread () from /usr/lib64/libespeak-ng.so.1
#10 0x00007f67266c2485 in start_thread () from /lib64/libc.so.6
#11 0x00007f672674610c in clone3 () from /lib64/libc.so.6
(gdb) where
#0  0x00007f672678ea6b in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#1  0x00007f6726492ffd in snd_pcm_area_copy (dst_area=0x7f672001fc90, dst_offset=18, src_area=0x7f672002a4c0, src_offset=0, samples=4026531840, format=SND_PCM_FORMAT_S16_LE) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm.c:3238
#2  0x00007f67264934af in snd_pcm_areas_copy (dst_areas=0x7f672001fca0, dst_offset=18, src_areas=0x7f672002a4d0, src_offset=0, channels=1, frames=18446744073709551608, format=SND_PCM_FORMAT_S16_LE) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm.c:3389
#3  0x00007f67264ba368 in snd_pcm_rate_commit_area (pcm=0x7f6720061cf0, rate=0x7f6720061b00, appl_offset=7508, size=10, slave_size=22) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm_rate.c:817
#4  0x00007f67264bb217 in snd_pcm_rate_drain (pcm=0x7f6720061cf0) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm_rate.c:1161
#5  0x00007f6726490548 in snd_pcm_drain (pcm=0x7f6720061700) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm.c:1359
#6  0x00007f67266347e2 in alsa_object_drain () from /usr/lib64/libpcaudio.so.0
#7  0x00007f6726873c4e in sync_espeak_Synth () from /usr/lib64/libespeak-ng.so.1
#8  0x00007f672688e813 in process_espeak_command () from /usr/lib64/libespeak-ng.so.1
#9  0x00007f672688f708 in say_thread () from /usr/lib64/libespeak-ng.so.1
#10 0x00007f67266c2485 in start_thread () from /lib64/libc.so.6
#11 0x00007f672674610c in clone3 () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007f672678ea6b in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f6726492ffd in snd_pcm_area_copy (dst_area=0x7f672001fc90, dst_offset=18, src_area=0x7f672002a4c0, src_offset=0, samples=4026531840, format=SND_PCM_FORMAT_S16_LE) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm.c:3238
        bytes = 536870896
        src = 0x7f672006ba50 "A\003+\002\205\001\252\001M\001\025\001P\002\317\001\227\001\324\375`\001\341\001Y\377P\002k\377\\"
        dst = 0x7f6720038814 "P\002\317\001\227\001\324\375`\001\341\001Y\377P\002k\377\\"
        width = 16
        src_step = 642318657
        dst_step = 32615
#2  0x00007f67264934af in snd_pcm_areas_copy (dst_areas=0x7f672001fca0, dst_offset=18, src_areas=0x7f672002a4d0, src_offset=0, channels=1, frames=18446744073709551608, format=SND_PCM_FORMAT_S16_LE) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm.c:3389
        step = 16
        src_addr = 0x7f672006ba50
        src_start = 0x7f672002a4c0
        channels1 = 0
        chns = 1
        dst_addr = 0x7f67200387f0
        dst_start = 0x7f672001fc90
        width = 16
#3  0x00007f67264ba368 in snd_pcm_rate_commit_area (pcm=0x7f6720061cf0, rate=0x7f6720061b00, appl_offset=7508, size=10, slave_size=22) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm_rate.c:817
        cont = 18
        areas = 0x7f672002a4c0
        slave_areas = 0x38c
        slave_offset = 13422172416
        xfer = 2199023255787
        slave_frames = 18446744073709551615
        result = 140080984498990
#4  0x00007f67264bb217 in snd_pcm_rate_drain (pcm=0x7f6720061cf0) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm_rate.c:1161
        psize = 10
        spsize = 22
        err = 1
        sw_params = {tstamp_mode = 0, period_step = 1, sleep_min = 0, avail_min = 1, xfer_align = 1, start_threshold = 2, stop_threshold = 16384, silence_threshold = 0, silence_size = 0, boundary = 4611686018427387904, proto = 131087, tstamp_type = 1, reserved = '\000' <repeats 55 times>}
        size = 10
        ofs = 7508
        saved_avail_min = 1024
        commit_err = 0
        rate = 0x7f6720061b00
#5  0x00007f6726490548 in snd_pcm_drain (pcm=0x7f6720061700) at /mnt/nocrypt/var/tmp/portage/portage/media-libs/alsa-lib-1.2.7.2-r1/work/alsa-lib-1.2.7.2/src/pcm/pcm.c:1359
        err = 0
#6  0x00007f67266347e2 in alsa_object_drain () from /usr/lib64/libpcaudio.so.0
No symbol table info available.
#7  0x00007f6726873c4e in sync_espeak_Synth () from /usr/lib64/libespeak-ng.so.1
No symbol table info available.
#8  0x00007f672688e813 in process_espeak_command () from /usr/lib64/libespeak-ng.so.1
No symbol table info available.
#9  0x00007f672688f708 in say_thread () from /usr/lib64/libespeak-ng.so.1
No symbol table info available.
#10 0x00007f67266c2485 in start_thread () from /lib64/libc.so.6
No symbol table info available.
#11 0x00007f672674610c in clone3 () from /lib64/libc.so.6
No symbol table info available.
(gdb) quit
```

Does it help?

**Comment by perexg** [comment]
Thanks the commit 9253f08fb784ad6a8b67b63e64732cb2f5694b6a should fix this issue. Thank you for your report.
